//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SSO_Modelo.Modelo
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;

    public partial class SSOEntities : DbContext
    {
        public SSOEntities()
            : base("name=SSOEntities")
        {
        }

        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }

        public virtual DbSet<SSO_auditoria> SSO_auditoria { get; set; }
        public virtual DbSet<SSO_code> SSO_code { get; set; }
        public virtual DbSet<SSO_federada> SSO_federada { get; set; }
        public virtual DbSet<SSO_redSocial> SSO_redSocial { get; set; }
        public virtual DbSet<SSO_servicios> SSO_servicios { get; set; }
        public virtual DbSet<SSO_usuario> SSO_usuario { get; set; }
        public virtual DbSet<SSO_usuarioCnx> SSO_usuarioCnx { get; set; }
        public virtual DbSet<SSO_usuarioFederada> SSO_usuarioFederada { get; set; }
        public virtual DbSet<SSO_usuarioRed> SSO_usuarioRed { get; set; }
        public virtual DbSet<SSO_variable> SSO_variable { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<SSO_usuarioClave> SSO_usuarioClave { get; set; }
    }
}
