//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SSO_Modelo.Modelo
{
    using System;
    using System.Collections.Generic;

    public partial class SSO_auditoria
    {
        public int auditoria_id { get; set; }
        public string auditoria_tablaNombre { get; set; }
        public string auditoria_operacion { get; set; }
        public System.DateTime auditoria_fechaOperacion { get; set; }
        public string auditoria_usuario { get; set; }
    }
}
