//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SSO_Modelo.Modelo
{
    using System.Collections.Generic;

    public partial class SSO_federada
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SSO_federada()
        {
            this.SSO_usuarioFederada = new HashSet<SSO_usuarioFederada>();
        }

        public int federada_id { get; set; }
        public string federada_nombre { get; set; }
        public string federada_url { get; set; }
        public string federada_descripcion { get; set; }
        public bool federada_estado { get; set; }
        public string federada_api { get; set; }
        public string federada_codigo { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SSO_usuarioFederada> SSO_usuarioFederada { get; set; }
    }
}
