//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SSO_Modelo.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class SSO_usuarioRed
    {
        public int usuarioRed_usuario_id { get; set; }
        public int usuarioRed_redSocial_id { get; set; }
        public string usuarioRed_correo_usuario { get; set; }
        public string usuarioRed_nombre_usuario { get; set; }
        public string usuarioRed_imagenUrl { get; set; }
        public System.DateTime usuarioRed_fecha { get; set; }
    
        public virtual SSO_redSocial SSO_redSocial { get; set; }
        public virtual SSO_usuario SSO_usuario { get; set; }
    }
}
