//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SSO_Modelo.Modelo
{
    using System;
    using System.Collections.Generic;

    public partial class SSO_redSocial
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SSO_redSocial()
        {
            this.SSO_usuarioRed = new HashSet<SSO_usuarioRed>();
        }

        public int redSocial_id { get; set; }
        public string redSocial_nombre { get; set; }
        public string redSocial_idApi { get; set; }
        public string redSocial_secretApi { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SSO_usuarioRed> SSO_usuarioRed { get; set; }
    }
}
