//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SSO_Modelo.Modelo
{
    using System;
    using System.Collections.Generic;

    public partial class SSO_usuario
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SSO_usuario()
        {
            this.SSO_code = new HashSet<SSO_code>();
            this.SSO_usuarioFederada = new HashSet<SSO_usuarioFederada>();
            this.SSO_usuarioCnx = new HashSet<SSO_usuarioCnx>();
            this.SSO_usuarioRed = new HashSet<SSO_usuarioRed>();
            this.SSO_usuarioClave = new HashSet<SSO_usuarioClave>();
        }

        public int usuario_id { get; set; }
        public string usuario_login { get; set; }
        public string usuario_nombre { get; set; }
        public string usuario_apPaterno { get; set; }
        public string usuario_apMaterno { get; set; }
        public string usuario_correoUPC { get; set; }
        public string usuario_correoPersonal { get; set; }
        public string usuario_telefono { get; set; }
        public bool usuario_estado { get; set; }
        public bool usuario_flagAsociarRedes { get; set; }
        public Nullable<bool> usuario_flagRecPas { get; set; }
        public string usuario_tipo { get; set; }
        public Nullable<System.DateTime> usuario_ultActDatos { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SSO_code> SSO_code { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SSO_usuarioFederada> SSO_usuarioFederada { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SSO_usuarioCnx> SSO_usuarioCnx { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SSO_usuarioRed> SSO_usuarioRed { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SSO_usuarioClave> SSO_usuarioClave { get; set; }
    }
}
