//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SSO_Modelo.Modelo
{
    public partial class SSO_servicios
    {
        public int servicio_id { get; set; }
        public string servicio_url { get; set; }
        public string servicio_tipo { get; set; }
        public string servicio_nombre { get; set; }
        public string servicio_descripcion { get; set; }
        public bool servicio_estado { get; set; }
    }
}
