//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SSO_BusinessLogic.WSAD {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AD.res", Namespace="http://schemas.datacontract.org/2004/07/")]
    [System.SerializableAttribute()]
    public partial class ADres : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private SSO_BusinessLogic.WSAD.ADAdUser AdUserField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int codeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string msgField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool okField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SSO_BusinessLogic.WSAD.ADAdUser AdUser {
            get {
                return this.AdUserField;
            }
            set {
                if ((object.ReferenceEquals(this.AdUserField, value) != true)) {
                    this.AdUserField = value;
                    this.RaisePropertyChanged("AdUser");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int code {
            get {
                return this.codeField;
            }
            set {
                if ((this.codeField.Equals(value) != true)) {
                    this.codeField = value;
                    this.RaisePropertyChanged("code");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string msg {
            get {
                return this.msgField;
            }
            set {
                if ((object.ReferenceEquals(this.msgField, value) != true)) {
                    this.msgField = value;
                    this.RaisePropertyChanged("msg");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool ok {
            get {
                return this.okField;
            }
            set {
                if ((this.okField.Equals(value) != true)) {
                    this.okField = value;
                    this.RaisePropertyChanged("ok");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AD.AdUser", Namespace="http://schemas.datacontract.org/2004/07/")]
    [System.SerializableAttribute()]
    public partial class ADAdUser : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CNField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailUPCField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LastNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OUField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PhoneField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SamAcountNameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CN {
            get {
                return this.CNField;
            }
            set {
                if ((object.ReferenceEquals(this.CNField, value) != true)) {
                    this.CNField = value;
                    this.RaisePropertyChanged("CN");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EmailUPC {
            get {
                return this.EmailUPCField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailUPCField, value) != true)) {
                    this.EmailUPCField = value;
                    this.RaisePropertyChanged("EmailUPC");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Id {
            get {
                return this.IdField;
            }
            set {
                if ((object.ReferenceEquals(this.IdField, value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LastName {
            get {
                return this.LastNameField;
            }
            set {
                if ((object.ReferenceEquals(this.LastNameField, value) != true)) {
                    this.LastNameField = value;
                    this.RaisePropertyChanged("LastName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string OU {
            get {
                return this.OUField;
            }
            set {
                if ((object.ReferenceEquals(this.OUField, value) != true)) {
                    this.OUField = value;
                    this.RaisePropertyChanged("OU");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Phone {
            get {
                return this.PhoneField;
            }
            set {
                if ((object.ReferenceEquals(this.PhoneField, value) != true)) {
                    this.PhoneField = value;
                    this.RaisePropertyChanged("Phone");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SamAcountName {
            get {
                return this.SamAcountNameField;
            }
            set {
                if ((object.ReferenceEquals(this.SamAcountNameField, value) != true)) {
                    this.SamAcountNameField = value;
                    this.RaisePropertyChanged("SamAcountName");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WSAD.IService")]
    public interface IService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/Auth", ReplyAction="http://tempuri.org/IService/AuthResponse")]
        SSO_BusinessLogic.WSAD.ADres Auth(string alias, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/Auth", ReplyAction="http://tempuri.org/IService/AuthResponse")]
        System.Threading.Tasks.Task<SSO_BusinessLogic.WSAD.ADres> AuthAsync(string alias, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetUser", ReplyAction="http://tempuri.org/IService/GetUserResponse")]
        SSO_BusinessLogic.WSAD.ADres GetUser(string alias);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetUser", ReplyAction="http://tempuri.org/IService/GetUserResponse")]
        System.Threading.Tasks.Task<SSO_BusinessLogic.WSAD.ADres> GetUserAsync(string alias);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/SetEmail", ReplyAction="http://tempuri.org/IService/SetEmailResponse")]
        SSO_BusinessLogic.WSAD.ADres SetEmail(string alias, string email);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/SetEmail", ReplyAction="http://tempuri.org/IService/SetEmailResponse")]
        System.Threading.Tasks.Task<SSO_BusinessLogic.WSAD.ADres> SetEmailAsync(string alias, string email);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/ChangePassword", ReplyAction="http://tempuri.org/IService/ChangePasswordResponse")]
        SSO_BusinessLogic.WSAD.ADres ChangePassword(string username, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/ChangePassword", ReplyAction="http://tempuri.org/IService/ChangePasswordResponse")]
        System.Threading.Tasks.Task<SSO_BusinessLogic.WSAD.ADres> ChangePasswordAsync(string username, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/ModifiedUsers", ReplyAction="http://tempuri.org/IService/ModifiedUsersResponse")]
        string ModifiedUsers(System.DateTime date);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/ModifiedUsers", ReplyAction="http://tempuri.org/IService/ModifiedUsersResponse")]
        System.Threading.Tasks.Task<string> ModifiedUsersAsync(System.DateTime date);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServiceChannel : SSO_BusinessLogic.WSAD.IService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceClient : System.ServiceModel.ClientBase<SSO_BusinessLogic.WSAD.IService>, SSO_BusinessLogic.WSAD.IService {
        
        public ServiceClient() {
        }
        
        public ServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public SSO_BusinessLogic.WSAD.ADres Auth(string alias, string password) {
            return base.Channel.Auth(alias, password);
        }
        
        public System.Threading.Tasks.Task<SSO_BusinessLogic.WSAD.ADres> AuthAsync(string alias, string password) {
            return base.Channel.AuthAsync(alias, password);
        }
        
        public SSO_BusinessLogic.WSAD.ADres GetUser(string alias) {
            return base.Channel.GetUser(alias);
        }
        
        public System.Threading.Tasks.Task<SSO_BusinessLogic.WSAD.ADres> GetUserAsync(string alias) {
            return base.Channel.GetUserAsync(alias);
        }
        
        public SSO_BusinessLogic.WSAD.ADres SetEmail(string alias, string email) {
            return base.Channel.SetEmail(alias, email);
        }
        
        public System.Threading.Tasks.Task<SSO_BusinessLogic.WSAD.ADres> SetEmailAsync(string alias, string email) {
            return base.Channel.SetEmailAsync(alias, email);
        }
        
        public SSO_BusinessLogic.WSAD.ADres ChangePassword(string username, string password) {
            return base.Channel.ChangePassword(username, password);
        }
        
        public System.Threading.Tasks.Task<SSO_BusinessLogic.WSAD.ADres> ChangePasswordAsync(string username, string password) {
            return base.Channel.ChangePasswordAsync(username, password);
        }
        
        public string ModifiedUsers(System.DateTime date) {
            return base.Channel.ModifiedUsers(date);
        }
        
        public System.Threading.Tasks.Task<string> ModifiedUsersAsync(System.DateTime date) {
            return base.Channel.ModifiedUsersAsync(date);
        }
    }
}
